// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

// Eagerly import all *_controller.js files in this directory tree
const modules = import.meta.glob("./**/*_controller.js", { eager: true });

for (const path in modules) {
  const controller = modules[path].default;
  const identifier = path
    .replace("./", "")
    .replace("_controller.js", "")
    .replace(/\//g, "--");
  application.register(identifier, controller);
}
